db.url=jdbc:postgresql://localhost:5432/quickexpense
db.user=postgres
db.password=12345678
db.driver=org.postgresql.Driver

# SMTP Email Configuration
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls=true
mail.sender.email=noreplycomitly@gmail.com
mail.sender.password=iaxi pifm ygfj fhel
mail.sender.name=QuickExpense

# App Configuration
app.name=QuickExpense
app.secret=CHANGE_ME_IN_PRODUCTION_BUT_THIS_IS_BETTER_THAN_CODE
